# Generated by Django 3.0.2 on 2020-03-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200303_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieshots',
            options={'verbose_name': 'Кадр из фильма', 'verbose_name_plural': 'Кадры из фильма'},
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='movies.Actor', verbose_name='актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Reviews', verbose_name='Родитель'),
        ),
    ]
